---
- name: Update packages
  ansible.builtin.package:
    update_cache: true
    upgrade: true
    cache_valid_time: 3600  # 60 min.
  register: update

- name: "Display package update result"
  ansible.builtin.debug: var=update.stdout
  when: update.stdout is defined
