---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: pihole-test
    dockerfile: Dockerfile
    image: debian-bullseye:local-test
    command: ""
    privileged: true
    pre_build_image: false

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    links:
      group_vars: ../../group_vars/

verifier:
  name: ansible
